import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { login, logout, me } from '../controllers/authController.js';
import { authenticateJWT } from '../middlewares/authMiddleware.js';
const router = Router();
const loginLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: true, legacyHeaders: false, message: { message: 'Muitas tentativas. Tente novamente mais tarde.' } });
router.post('/login', loginLimiter, login);
router.post('/logout', authenticateJWT, logout);
router.get('/me', authenticateJWT, me);
export default router;
