'use client';
/* eslint-disable react-hooks/set-state-in-effect -- API and localStorage are client-only external sources synchronized on mount. */

import dynamic from 'next/dynamic';
import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useMemo, useState } from 'react';
import ConfirmDialog from '../components/ConfirmDialog';
import DashboardPanel from '../components/DashboardPanel';
import Header from '../components/Header';
import KPISection from '../components/KPISection';
import LessonCard from '../components/LessonCard';
import LessonDetailPage from '../components/LessonDetailPage';
import LessonDrawer from '../components/LessonDrawer';
import { EmptyState, ListSkeleton } from '../components/LoadingStates';
import NewLessonForm from '../components/NewLessonForm';
import PlaceholderPanel from '../components/PlaceholderPanel';
import RoadmapCard from '../components/RoadmapCard';
import SearchFilters from '../components/SearchFilters';
import SimilarLessonsPanel from '../components/SimilarLessonsPanel';
import Sidebar from '../components/Sidebar';
import Toast from '../components/Toast';
import { useToast } from '../hooks/useToast';
import { findSimilarLessons } from '../lib/similarity';
import { getLessonHistory, registerChanges, registerCreation, registerDeletion } from '../services/lessonHistory';
import { apiFetch, clearToken, getToken } from '../services/api';

const AboutSystem = dynamic(() => import('../components/AboutSystem'), { loading: () => <div className="animate-pulse rounded-2xl bg-white p-10 shadow-sm" /> });
const emptyForm = { title: '', sector: '', description: '', cause: '', action: '', responsible: '', status: 'Aberta', image: '', attachment: '', occurrenceDate: '', client: '', project: '', product: '', partCode: '', category: '', priority: 'Média', defectType: '', severity: '', affectedQuantity: '', tags: '', method: '', analysisResponsible: '', containment: '', correction: '', preventiveAction: '', conclusionDate: '', closingResponsible: '', effectivenessValidation: '' };
const navigation = ['Dashboard', 'Lições Aprendidas', 'Nova Ocorrência', 'Indicadores', 'Auditorias', 'Configurações', 'Sobre o Sistema'];
const pageContent = { Dashboard: ['Dashboard executivo', 'Visão consolidada das lições aprendidas e desempenho operacional.'], 'Lições Aprendidas': ['Lições aprendidas', 'Consulte, filtre e mantenha o histórico de ocorrências industriais.'], 'Nova Ocorrência': ['Nova ocorrência', 'Registre uma lição aprendida para preservar o conhecimento operacional.'], Indicadores: ['Indicadores', 'Acompanhe a performance e a evolução dos processos.'], Auditorias: ['Auditorias', 'Rastreabilidade e conformidade operacional.'], Configurações: ['Configurações', 'Parâmetros e administração da plataforma.'], 'Sobre o Sistema': ['Sobre o sistema', 'Informações institucionais e tecnologias da plataforma.'] };

export default function Home() {
  const router = useRouter();
  const [lessons, setLessons] = useState([]); const [formData, setFormData] = useState(emptyForm); const [editingId, setEditingId] = useState(null); const [selectedMenu, setSelectedMenu] = useState('Dashboard'); const [search, setSearch] = useState(''); const [sectorFilter, setSectorFilter] = useState('Todos'); const [statusFilter, setStatusFilter] = useState('Todos'); const [isAuthenticated, setIsAuthenticated] = useState(false); const [currentUser, setCurrentUser] = useState(null); const [error, setError] = useState(''); const [isSaving, setIsSaving] = useState(false); const [isLoading, setIsLoading] = useState(true); const [authChecking, setAuthChecking] = useState(true); const [drawerLesson, setDrawerLesson] = useState(null); const [detailLesson, setDetailLesson] = useState(null); const [dialog, setDialog] = useState(null); const { toast, showToast, dismissToast } = useToast();

  const loadLessons = useCallback(async () => { setIsLoading(true); try { setError(''); const response = await apiFetch('/lessons'); if (!response.ok) throw new Error('Não foi possível carregar as lições.'); setLessons(await response.json()); } catch (loadError) { const message = `${loadError.message} Verifique se o backend está em execução.`; setError(message); showToast('error', message); } finally { setIsLoading(false); } }, [showToast]);
  useEffect(() => { loadLessons(); }, [loadLessons]);
  useEffect(() => { async function validateSession() { if (!getToken()) { router.replace('/login'); return; } try { const response = await apiFetch('/auth/me'); if (!response.ok) throw new Error('Sessão inválida.'); const data = await response.json(); setCurrentUser(data.user); setIsAuthenticated(true); } catch { clearToken(); router.replace('/login'); } finally { setAuthChecking(false); } } validateSession(); }, [router]);
  const filteredLessons = useMemo(() => lessons.filter((lesson) => { const query = search.toLowerCase(); const content = `${lesson.title} ${lesson.description || ''} ${lesson.cause || ''}`.toLowerCase(); return content.includes(query) && (sectorFilter === 'Todos' || lesson.sector === sectorFilter) && (statusFilter === 'Todos' || lesson.status === statusFilter); }), [lessons, search, sectorFilter, statusFilter]);
  const resetEdit = useCallback(() => { setEditingId(null); setFormData(emptyForm); }, []);
  const startEdit = useCallback((lesson) => { setDetailLesson(null); setEditingId(lesson.id); setFormData({ ...emptyForm, ...lesson }); setSelectedMenu('Nova Ocorrência'); window.scrollTo({ top: 0, behavior: 'smooth' }); }, []);
  const openDetail = useCallback((lesson) => setDetailLesson(lesson), []);
  async function saveLesson() { if (!formData.title.trim() || !formData.sector.trim()) { const message = 'Título e setor são obrigatórios.'; setError(message); showToast('warning', message); return; } setIsSaving(true); try { const previous = lessons.find((lesson) => lesson.id === editingId); const response = await apiFetch(`/lessons${editingId ? `/${editingId}` : ''}`, { method: editingId ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(formData) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Não foi possível salvar o registro.'); const savedLesson = { ...formData, ...data }; setLessons((items) => editingId ? items.map((item) => item.id === editingId ? savedLesson : item) : [savedLesson, ...items]); if (editingId) registerChanges(previous, savedLesson); else registerCreation(savedLesson); resetEdit(); setSelectedMenu('Lições Aprendidas'); showToast('success', editingId ? 'Ocorrência atualizada com sucesso.' : 'Ocorrência cadastrada com sucesso.'); } catch (saveError) { setError(saveError.message); showToast('error', saveError.message); } finally { setIsSaving(false); } }
  async function performDelete(id) { const lesson = lessons.find((item) => item.id === id); try { const response = await apiFetch(`/lessons/${id}`, { method: 'DELETE' }); if (!response.ok) throw new Error('Não foi possível excluir o registro.'); if (lesson) registerDeletion(lesson); setLessons((items) => items.filter((item) => item.id !== id)); if (editingId === id) resetEdit(); if (detailLesson?.id === id) setDetailLesson(null); showToast('success', 'Ocorrência excluída com sucesso.'); } catch (deleteError) { setError(deleteError.message); showToast('error', deleteError.message); } }
  function requestDelete(id) { setDialog({ type: 'delete', id, title: 'Excluir ocorrência?', message: 'Esta ação remove a ocorrência da lista e não pode ser desfeita.', confirmLabel: 'Excluir ocorrência', danger: true }); }
  function requestCancelEdit() { if (!editingId) return resetEdit(); setDialog({ type: 'cancel', title: 'Cancelar edição?', message: 'As alterações não salvas serão descartadas.', confirmLabel: 'Descartar alterações' }); }
  function confirmDialog() { if (dialog.type === 'delete') performDelete(dialog.id); if (dialog.type === 'cancel') resetEdit(); if (dialog.type === 'navigate') { resetEdit(); setDetailLesson(null); setSelectedMenu(dialog.menu); } setDialog(null); }
  function selectMenu(menu) { if (editingId && menu !== 'Nova Ocorrência') { setDialog({ type: 'navigate', menu, title: 'Sair da edição?', message: 'As alterações não salvas serão descartadas.', confirmLabel: 'Sair sem salvar' }); return; } if (editingId && menu === 'Nova Ocorrência') return; setDetailLesson(null); setSelectedMenu(menu); if (menu === 'Nova Ocorrência') resetEdit(); }
  async function handleLogout() { try { await apiFetch('/auth/logout', { method: 'POST' }); } finally { clearToken(); setCurrentUser(null); setIsAuthenticated(false); router.replace('/login'); } }
  if (authChecking || !isAuthenticated) return <div className="grid min-h-screen place-items-center bg-slate-950 text-sm font-semibold text-slate-300">Validando sessão...</div>;
  const resolvedCount = lessons.filter((lesson) => lesson.status === 'Resolvido' || lesson.status === 'Encerrada').length; const analysisCount = lessons.filter((lesson) => lesson.status === 'Em análise' || lesson.status === 'Em Investigação').length; const similarLessons = findSimilarLessons(formData, lessons, editingId); const [title, subtitle] = pageContent[selectedMenu]; const breadcrumbs = selectedMenu === 'Dashboard' ? ['Dashboard'] : ['Dashboard', selectedMenu];
  return <div className="min-h-screen bg-slate-100"><div className="flex"><Sidebar selectedMenu={selectedMenu} onSelect={selectMenu} /><main className="min-w-0 flex-1"><div className="border-b border-slate-200 bg-white px-4 py-3 lg:hidden"><div className="flex gap-2 overflow-x-auto">{navigation.map((item) => <button key={item} title={item} onClick={() => selectMenu(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold ${selectedMenu === item ? 'bg-slate-950 text-white' : 'bg-slate-100 text-slate-600'}`}>{item}</button>)}</div></div><div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8">{detailLesson ? <LessonDetailPage lesson={detailLesson} lessons={lessons} history={getLessonHistory(detailLesson.id)} onBack={() => setDetailLesson(null)} onEdit={startEdit} onOpenLesson={openDetail} /> : <><Header currentUser={currentUser} handleLogout={handleLogout} title={title} subtitle={subtitle} breadcrumbs={breadcrumbs} />{error && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{selectedMenu === 'Dashboard' && <>{isLoading ? <ListSkeleton /> : <><KPISection lessons={lessons} resolvedCount={resolvedCount} analysisCount={analysisCount} /><DashboardPanel lessons={lessons} /></>}</>}{selectedMenu === 'Lições Aprendidas' && <><SearchFilters search={search} setSearch={setSearch} sectorFilter={sectorFilter} setSectorFilter={setSectorFilter} statusFilter={statusFilter} setStatusFilter={setStatusFilter} />{isLoading ? <ListSkeleton /> : <section className="space-y-5">{filteredLessons.length ? filteredLessons.map((lesson) => <LessonCard key={lesson.id} lesson={lesson} onOpen={openDetail} onEdit={startEdit} onDelete={requestDelete} />) : <EmptyState onCreate={() => selectMenu('Nova Ocorrência')} />}</section>}</>}{selectedMenu === 'Nova Ocorrência' && <div className="grid gap-6 2xl:grid-cols-3"><div className="2xl:col-span-2"><NewLessonForm formData={formData} setFormData={setFormData} onSave={saveLesson} onCancel={requestCancelEdit} isEditing={Boolean(editingId)} isSaving={isSaving} /></div><aside className="space-y-6"><SimilarLessonsPanel matches={similarLessons} onOpenLesson={setDrawerLesson} /><RoadmapCard /></aside></div>}{['Indicadores', 'Auditorias', 'Configurações'].includes(selectedMenu) && <PlaceholderPanel type={selectedMenu} />}{selectedMenu === 'Sobre o Sistema' && <AboutSystem />}</>}</div></main></div><LessonDrawer lesson={drawerLesson} onClose={() => setDrawerLesson(null)} /><ConfirmDialog dialog={dialog} onConfirm={confirmDialog} onCancel={() => setDialog(null)} /><Toast toast={toast} onDismiss={dismissToast} /></div>;
}
