import { useEffect, useRef, useState } from 'react';
import { API_URL, apiFetch, getToken } from '../services/api';
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps -- a lista é sincronizada com uma fonte externa autenticada ao montar o painel. */

const allowed = '.jpg,.jpeg,.png,.webp,.pdf,.docx,.xlsx';
export default function AttachmentsPanel({ lessonId }) {
  const [files, setFiles] = useState([]); const [error, setError] = useState(''); const [progress, setProgress] = useState(0); const [uploading, setUploading] = useState(false); const input = useRef(null);
  async function loadFiles() { const response = await apiFetch(`/lessons/${lessonId}/files`); if (!response.ok) { const data = await response.json(); setError(data.message); return; } setFiles(await response.json()); }
  useEffect(() => { loadFiles(); }, [lessonId]);
  function upload(event) { const file = event.target.files?.[0]; if (!file) return; setError(''); setUploading(true); setProgress(0); const body = new FormData(); body.append('file', file); const request = new XMLHttpRequest(); request.open('POST', `${API_URL}/lessons/${lessonId}/files`); request.setRequestHeader('Authorization', `Bearer ${getToken()}`); request.upload.onprogress = (progressEvent) => { if (progressEvent.lengthComputable) setProgress(Math.round((progressEvent.loaded / progressEvent.total) * 100)); }; request.onload = () => { setUploading(false); input.current.value = ''; if (request.status >= 200 && request.status < 300) { setProgress(100); loadFiles(); } else { setError(JSON.parse(request.responseText || '{}').message || 'Não foi possível enviar o arquivo.'); } }; request.onerror = () => { setUploading(false); setError('Falha de conexão durante o upload.'); }; request.send(body); }
  async function remove(id) { if (!window.confirm('Excluir este anexo?')) return; const response = await apiFetch(`/files/${id}`, { method: 'DELETE' }); if (!response.ok) { const data = await response.json(); return setError(data.message); } loadFiles(); }
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.15em] text-cyan-700">EVIDÊNCIAS</p><h2 className="mt-2 text-xl font-bold text-slate-900">Anexos</h2><p className="mt-1 text-sm text-slate-500">JPG, PNG, WEBP, PDF, DOCX e XLSX · máximo de 20 MB.</p></div><input ref={input} type="file" accept={allowed} onChange={upload} className="hidden" /><button onClick={() => input.current?.click()} disabled={uploading} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{uploading ? 'Enviando...' : 'Adicionar arquivo'}</button></div>{uploading && <div className="mt-5"><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div style={{ width: `${progress}%` }} className="h-full rounded-full bg-cyan-600 transition-all" /></div><p className="mt-2 text-xs text-slate-500">Upload: {progress}%</p></div>}{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 space-y-3">{files.length ? files.map((file) => <article key={file.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><div className="min-w-0"><p className="truncate font-semibold text-slate-800">📎 {file.originalName}</p><p className="mt-1 text-xs text-slate-500">{Math.ceil(file.fileSize / 1024)} KB · {new Date(file.createdAt).toLocaleString('pt-BR')}</p></div><div className="flex gap-2"><a href={file.publicUrl} target="_blank" rel="noreferrer" className="rounded-lg bg-white px-3 py-2 text-sm font-semibold text-cyan-700 shadow-sm">Visualizar</a><a href={file.publicUrl} download className="rounded-lg bg-white px-3 py-2 text-sm font-semibold text-slate-700 shadow-sm">Download</a><button onClick={() => remove(file.id)} className="rounded-lg bg-red-50 px-3 py-2 text-sm font-semibold text-red-700">Excluir</button></div></article>) : <p className="rounded-xl border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">Nenhum anexo enviado.</p>}</div></section>;
}
