import { useMemo, useState } from 'react';
import { lessonTabs } from '../lib/lessonTabs';
import { findSimilarLessons } from '../lib/similarity';
import AttachmentsPanel from './AttachmentsPanel';
import LessonHeader from './LessonHeader';
import LessonHistory from './LessonHistory';
import LessonSummaryCard from './LessonSummaryCard';
import LessonWorkflow from './LessonWorkflow';
import RelatedLessonsTab from './RelatedLessonsTab';

const detailTabs = [...lessonTabs, 'Ocorrências Relacionadas', 'Histórico'];
export default function LessonDetailPage({ lesson, lessons, history, onBack, onEdit, onOpenLesson }) {
  const [activeTab, setActiveTab] = useState('Identificação'); const matches = useMemo(() => findSimilarLessons(lesson, lessons, lesson.id), [lesson, lessons]);
  return <div className="space-y-6"><LessonHeader lesson={lesson} onBack={onBack} onEdit={() => onEdit(lesson)} /><section className="rounded-2xl border border-slate-200 bg-white px-5 py-5 shadow-sm"><p className="text-xs font-bold tracking-[0.15em] text-cyan-700">WORKFLOW DA OCORRÊNCIA</p><div className="mt-4"><LessonWorkflow status={lesson.status} /></div></section><div className="grid gap-6 lg:grid-cols-4"><LessonSummaryCard lesson={lesson} /><section className="min-w-0 lg:col-span-3"><nav className="flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-sm">{detailTabs.map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={`shrink-0 rounded-xl px-3 py-2.5 text-sm font-semibold transition ${activeTab === tab ? 'bg-slate-950 text-white' : 'text-slate-500 hover:bg-slate-100 hover:text-slate-900'}`}>{tab}</button>)}</nav><div className="mt-5">{activeTab === 'Ocorrências Relacionadas' ? <RelatedLessonsTab matches={matches} onOpen={onOpenLesson} /> : activeTab === 'Histórico' ? <LessonHistory lesson={lesson} history={history} /> : activeTab === 'Evidências' ? <AttachmentsPanel lessonId={lesson.id} /> : <DetailTab tab={activeTab} lesson={lesson} />}</div></section></div></div>;
}
function DetailTab({ tab, lesson }) { const content = { Identificação: [['Cliente', lesson.client], ['Projeto', lesson.project], ['Produto', lesson.product], ['Código da peça', lesson.partCode], ['Setor', lesson.sector], ['Categoria', lesson.category], ['Prioridade', lesson.priority], ['Data da ocorrência', lesson.occurrenceDate]], Problema: [['Título', lesson.title], ['Descrição', lesson.description], ['Tipo de defeito', lesson.defectType], ['Gravidade', lesson.severity], ['Quantidade afetada', lesson.affectedQuantity], ['Tags', lesson.tags]], Investigação: [['Causa raiz', lesson.cause], ['Método utilizado', lesson.method], ['Responsável pela análise', lesson.analysisResponsible], ['Responsável pela ocorrência', lesson.responsible]], 'Plano de Ação': [['Contenção', lesson.containment], ['Correção', lesson.correction], ['Ação corretiva', lesson.action], ['Ação preventiva', lesson.preventiveAction]], Encerramento: [['Data de conclusão', lesson.conclusionDate], ['Responsável pelo encerramento', lesson.closingResponsible], ['Status', lesson.status], ['Validação da eficácia', lesson.effectivenessValidation]] }; return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-slate-900">{tab}</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{content[tab].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{value || 'Não informado.'}</p></div>)}</div></section>; }
