import { useRef, useState } from 'react';
/* eslint-disable @next/next/no-img-element -- local photo previews use browser object URLs, which next/image cannot optimize. */
import { lessonTabs } from '../lib/lessonTabs';
import LessonWorkflow, { workflowSteps } from './LessonWorkflow';

const sectors = ['Pintura', 'Laboratório de Cor', 'Produção', 'Injetoras', 'Manutenção'];
const documentTypes = '.pdf,.doc,.docx,.xls,.xlsx,.txt';

export default function NewLessonForm({ formData, setFormData, onSave, onCancel, isEditing, isSaving }) {
  const [activeTab, setActiveTab] = useState('Identificação'); const [photos, setPhotos] = useState([]); const [documents, setDocuments] = useState([]);
  const photoInput = useRef(null); const documentInput = useRef(null); const setField = (field, value) => setFormData({ ...formData, [field]: value });
  const generatedCode = isEditing ? formData.id : 'LA-AUTO';
  function addPhotos(event) { const files = Array.from(event.target.files || []); const added = files.map((file) => ({ id: `${file.name}-${file.lastModified}`, name: file.name, url: URL.createObjectURL(file) })); setPhotos((items) => [...items, ...added]); if (!formData.image && added[0]) setField('image', added[0].url); event.target.value = ''; }
  function removePhoto(id) { const photo = photos.find((item) => item.id === id); if (photo) URL.revokeObjectURL(photo.url); const remaining = photos.filter((item) => item.id !== id); setPhotos(remaining); if (formData.image === photo?.url) setField('image', remaining[0]?.url || ''); }
  function addDocuments(event) { const files = Array.from(event.target.files || []); const added = files.map((file) => ({ id: `${file.name}-${file.lastModified}`, name: file.name })); const next = [...documents, ...added]; setDocuments(next); setField('attachment', next.map((file) => file.name).join(', ')); event.target.value = ''; }
  function removeDocument(id) { const next = documents.filter((file) => file.id !== id); setDocuments(next); setField('attachment', next.map((file) => file.name).join(', ')); }
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-5 sm:px-7"><p className="text-xs font-bold tracking-[0.15em] text-cyan-700">FICHA COMPLETA DE LIÇÃO APRENDIDA</p><div className="mt-2 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-2xl font-bold text-slate-900">{isEditing ? 'Editar ocorrência' : 'Nova ocorrência'}</h2><span className="w-fit rounded-lg bg-slate-100 px-3 py-1.5 text-sm font-bold text-slate-700">{generatedCode}</span></div><div className="mt-6"><LessonWorkflow status={formData.status} /></div></div><nav aria-label="Etapas da ficha" className="flex gap-1 overflow-x-auto border-b border-slate-100 px-3 py-3 sm:px-5">{lessonTabs.map((tab, index) => <button key={tab} onClick={() => setActiveTab(tab)} className={`shrink-0 rounded-lg px-3 py-2 text-sm font-semibold transition ${activeTab === tab ? 'bg-slate-950 text-white shadow-sm' : 'text-slate-500 hover:bg-slate-100 hover:text-slate-900'}`}><span className="mr-1.5 text-xs opacity-70">{index + 1}</span>{tab}</button>)}</nav><div className="p-5 sm:p-7">{activeTab === 'Identificação' && <Identification form={formData} setField={setField} code={generatedCode} />}{activeTab === 'Problema' && <Problem form={formData} setField={setField} />}{activeTab === 'Investigação' && <Investigation form={formData} setField={setField} />}{activeTab === 'Plano de Ação' && <ActionPlan form={formData} setField={setField} />}{activeTab === 'Evidências' && <Evidence photos={photos} documents={documents} photoInput={photoInput} documentInput={documentInput} addPhotos={addPhotos} removePhoto={removePhoto} addDocuments={addDocuments} removeDocument={removeDocument} />}{activeTab === 'Encerramento' && <Closing form={formData} setField={setField} />}<div className="mt-8 flex flex-wrap gap-3 border-t border-slate-100 pt-6"><button onClick={onSave} disabled={isSaving} className="rounded-xl bg-slate-950 px-6 py-3.5 font-semibold text-white transition hover:bg-slate-800 disabled:opacity-50">{isSaving ? 'Salvando...' : isEditing ? 'Salvar alterações' : 'Salvar registro'}</button>{isEditing && <button onClick={onCancel} className="rounded-xl bg-slate-100 px-5 py-3.5 font-semibold text-slate-700">Cancelar</button>}</div></div></section>;
}
function Field({ label, children, hint }) { return <label className="block text-sm font-semibold text-slate-700"><span className="mb-2 block">{label}</span>{children}{hint && <span className="mt-1 block text-xs font-normal text-slate-400">{hint}</span>}</label>; }
function Input({ form, setField, field, label, type = 'text', placeholder, readOnly = false }) { return <Field label={label}><input type={type} value={form[field] || ''} onChange={(event) => setField(field, event.target.value)} placeholder={placeholder} readOnly={readOnly} className={`field ${readOnly ? 'bg-slate-100 text-slate-500' : ''}`} /></Field>; }
function TextArea({ form, setField, field, label, placeholder }) { return <Field label={label}><textarea rows={5} value={form[field] || ''} onChange={(event) => setField(field, event.target.value)} placeholder={placeholder} className="field resize-y" /></Field>; }
function Identification({ form, setField, code }) { return <TabIntro title="Identificação da ocorrência" description="Dados de rastreabilidade e classificação inicial."><div className="grid gap-5 md:grid-cols-2"><Field label="Código da Lição"><input value={code} readOnly className="field bg-slate-100 text-slate-500" /></Field><Input form={form} setField={setField} field="occurrenceDate" label="Data da ocorrência" type="date" /><Input form={form} setField={setField} field="client" label="Cliente" placeholder="Cliente ou unidade" /><Input form={form} setField={setField} field="project" label="Projeto" placeholder="Projeto relacionado" /><Input form={form} setField={setField} field="product" label="Produto" placeholder="Produto afetado" /><Input form={form} setField={setField} field="partCode" label="Código da peça" placeholder="Ex.: 12345-A" /><Field label="Setor"><select value={form.sector} onChange={(event) => setField('sector', event.target.value)} className="field"><option value="">Selecionar setor</option>{sectors.map((sector) => <option key={sector}>{sector}</option>)}</select></Field><Input form={form} setField={setField} field="category" label="Categoria" placeholder="Ex.: Qualidade, Processo" /><Field label="Prioridade"><select value={form.priority} onChange={(event) => setField('priority', event.target.value)} className="field"><option>Baixa</option><option>Média</option><option>Alta</option><option>Crítica</option></select></Field></div></TabIntro>; }
function Problem({ form, setField }) { return <TabIntro title="Descrição do problema" description="Registre o que aconteceu e o impacto da ocorrência."><div className="space-y-5"><Input form={form} setField={setField} field="title" label="Título *" placeholder="Resumo objetivo da ocorrência" /><TextArea form={form} setField={setField} field="description" label="Descrição" placeholder="Descreva a ocorrência, contexto e impacto." /><div className="grid gap-5 md:grid-cols-3"><Input form={form} setField={setField} field="defectType" label="Tipo de defeito" placeholder="Ex.: Mancha" /><Field label="Gravidade"><select value={form.severity} onChange={(event) => setField('severity', event.target.value)} className="field"><option value="">Selecionar</option><option>Baixa</option><option>Média</option><option>Alta</option><option>Crítica</option></select></Field><Input form={form} setField={setField} field="affectedQuantity" label="Quantidade afetada" type="number" placeholder="0" /></div><Input form={form} setField={setField} field="tags" label="Tags" placeholder="Separe as tags por vírgula" /></div></TabIntro>; }
function Investigation({ form, setField }) { return <TabIntro title="Investigação e análise" description="Documente a análise conduzida e a causa identificada."><div className="space-y-5"><TextArea form={form} setField={setField} field="cause" label="Causa raiz" placeholder="Causa identificada após investigação" /><div className="grid gap-5 md:grid-cols-2"><Field label="Método utilizado"><select value={form.method} onChange={(event) => setField('method', event.target.value)} className="field"><option value="">Selecionar método</option>{['5 Porquês', 'Ishikawa', '8D', 'FMEA', 'Outro'].map((method) => <option key={method}>{method}</option>)}</select></Field><Input form={form} setField={setField} field="analysisResponsible" label="Responsável pela análise" placeholder="Nome do responsável" /></div><Input form={form} setField={setField} field="responsible" label="Responsável pela ocorrência" placeholder="Nome do responsável principal" /></div></TabIntro>; }
function ActionPlan({ form, setField }) { return <TabIntro title="Plano de ação" description="Ações para eliminar o efeito, corrigir a causa e prevenir recorrências."><div className="grid gap-5 md:grid-cols-2"><TextArea form={form} setField={setField} field="containment" label="Contenção" placeholder="Ação imediata para conter o impacto" /><TextArea form={form} setField={setField} field="correction" label="Correção" placeholder="Correção aplicada" /><TextArea form={form} setField={setField} field="action" label="Ação corretiva" placeholder="Ação para eliminar a causa raiz" /><TextArea form={form} setField={setField} field="preventiveAction" label="Ação preventiva" placeholder="Ação para evitar ocorrências semelhantes" /></div></TabIntro>; }
function Evidence({ photos, documents, photoInput, documentInput, addPhotos, removePhoto, addDocuments, removeDocument }) { return <TabIntro title="Evidências da ocorrência" description="Organize os registros visuais e documentos técnicos de apoio."><div className="grid gap-5 xl:grid-cols-2"><UploadCard icon="📷" title="Fotografias" description="Imagens da ocorrência e evidências visuais." action="Adicionar fotos" onClick={() => photoInput.current?.click()}><input ref={photoInput} type="file" accept="image/*" multiple onChange={addPhotos} className="hidden" />{photos.length ? <div className="grid grid-cols-2 gap-3">{photos.map((photo) => <div key={photo.id} className="group relative overflow-hidden rounded-xl"><img src={photo.url} alt={photo.name} className="h-28 w-full object-cover" /><button onClick={() => removePhoto(photo.id)} className="absolute right-2 top-2 rounded-lg bg-slate-950/80 px-2 py-1 text-xs text-white opacity-0 transition group-hover:opacity-100">Remover</button></div>)}</div> : <EmptyUpload label="Nenhuma fotografia adicionada." />}</UploadCard><UploadCard icon="📄" title="Documentos e relatórios" description="PDF, DOC, DOCX, XLS, XLSX e TXT." action="Adicionar documento" onClick={() => documentInput.current?.click()}><input ref={documentInput} type="file" accept={documentTypes} multiple onChange={addDocuments} className="hidden" />{documents.length ? <ul className="space-y-2">{documents.map((document) => <li key={document.id} className="flex items-center justify-between rounded-lg bg-white px-3 py-2 text-sm text-slate-600 shadow-sm"><span className="truncate">📄 {document.name}</span><button onClick={() => removeDocument(document.id)} className="ml-3 text-xs font-semibold text-red-600">Remover</button></li>)}</ul> : <EmptyUpload label="Nenhum documento ou planilha anexado." />}</UploadCard><div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5 xl:col-span-2"><p className="font-bold text-slate-800">🎬 Vídeos</p><p className="mt-1 text-sm text-slate-500">Estrutura preparada para anexar vídeos em uma próxima evolução.</p></div></div></TabIntro>; }
function Closing({ form, setField }) { return <TabIntro title="Encerramento e eficácia" description="Formalize a conclusão da ocorrência e valide o resultado."><div className="grid gap-5 md:grid-cols-2"><Input form={form} setField={setField} field="conclusionDate" label="Data de conclusão" type="date" /><Input form={form} setField={setField} field="closingResponsible" label="Responsável pelo encerramento" placeholder="Nome do responsável" /><Field label="Status"><select value={form.status} onChange={(event) => setField('status', event.target.value)} className="field">{workflowSteps.map((status) => <option key={status}>{status}</option>)}<option>Resolvido</option></select></Field></div><div className="mt-5"><TextArea form={form} setField={setField} field="effectivenessValidation" label="Validação da eficácia" placeholder="Descreva como a eficácia da ação foi validada." /></div></TabIntro>; }
function TabIntro({ title, description, children }) { return <div><div className="mb-6"><h3 className="text-xl font-bold text-slate-900">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div>{children}</div>; }
function UploadCard({ icon, title, description, action, onClick, children }) { return <section className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold text-slate-800">{icon} {title}</p><p className="mt-1 text-sm text-slate-500">{description}</p></div><button type="button" onClick={onClick} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 transition hover:border-cyan-500 hover:text-cyan-700">{action}</button></div>{children}</section>; }
function EmptyUpload({ label }) { return <p className="rounded-xl border border-dashed border-slate-300 p-4 text-center text-sm text-slate-500">{label}</p>; }
