import { useEffect, useState } from 'react';
import { apiFetch } from '../services/api';
/* eslint-disable react-hooks/set-state-in-effect -- a lista é sincronizada com uma fonte externa autenticada ao montar a tela. */

const emptyUser = { name: '', email: '', password: '', role: 'Colaborador', active: true };
const roles = ['Administrador', 'Gestor', 'Colaborador', 'Auditor'];

export default function UsersAdmin({ currentUser }) {
  const [users, setUsers] = useState([]); const [form, setForm] = useState(emptyUser); const [editing, setEditing] = useState(null); const [error, setError] = useState('');
  async function loadUsers() { const response = await apiFetch('/users'); const data = await response.json(); if (!response.ok) return setError(data.message); setUsers(data); }
  useEffect(() => { loadUsers(); }, []);
  if (currentUser.role !== 'Administrador') return <section className="rounded-2xl bg-white p-8 shadow-sm"><h2 className="text-xl font-bold text-slate-900">Acesso restrito</h2><p className="mt-2 text-slate-500">A administração de usuários é permitida somente para Administradores.</p></section>;
  async function save(event) { event.preventDefault(); setError(''); const response = await apiFetch(`/users${editing ? `/${editing}` : ''}`, { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) return setError(data.message); setForm(emptyUser); setEditing(null); loadUsers(); }
  function edit(user) { setEditing(user.id); setForm({ ...user, password: '' }); }
  async function remove(id) { if (!window.confirm('Excluir este usuário?')) return; await apiFetch(`/users/${id}`, { method: 'DELETE' }); loadUsers(); }
  return <div className="grid gap-6 xl:grid-cols-3"><form onSubmit={save} className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-slate-900">{editing ? 'Editar usuário' : 'Novo usuário'}</h2>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 space-y-4"><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Nome" className="field" /><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="E-mail" className="field" /><input required={!editing} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder={editing ? 'Nova senha (opcional)' : 'Senha inicial'} className="field" /><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} className="field">{roles.map((role) => <option key={role}>{role}</option>)}</select><label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} /> Usuário ativo</label><button className="w-full rounded-xl bg-slate-950 py-3 font-semibold text-white">{editing ? 'Salvar alterações' : 'Cadastrar usuário'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(emptyUser); }} className="w-full rounded-xl bg-slate-100 py-3 font-semibold text-slate-700">Cancelar</button>}</div></form><section className="overflow-hidden rounded-2xl bg-white shadow-sm xl:col-span-2"><div className="border-b border-slate-100 p-6"><h2 className="text-xl font-bold text-slate-900">Usuários cadastrados</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Nome</th><th className="p-4">Perfil</th><th className="p-4">Status</th><th className="p-4">Ações</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-t border-slate-100"><td className="p-4"><p className="font-semibold text-slate-800">{user.name}</p><p className="text-slate-500">{user.email}</p></td><td className="p-4">{user.role}</td><td className="p-4">{user.active ? 'Ativo' : 'Inativo'}</td><td className="p-4"><div className="flex gap-2"><button onClick={() => edit(user)} className="font-semibold text-cyan-700">Editar</button><button onClick={() => { setEditing(user.id); setForm({ ...user, password: 'Admin@123' }); }} className="font-semibold text-amber-700">Resetar senha</button><button onClick={() => remove(user.id)} className="font-semibold text-red-700">Excluir</button></div></td></tr>)}</tbody></table></div></section></div>;
}
